### ISSUE TITLE
Transferring studies between computers

### ISSUE THREAD

**Issue by jfg14** [egonet/egonet#6]
I'm using the program for data analysis at my job. I'll be leaving in a few months to pursue other things. However, I would like someone else to be able to continue my study as it is long term. Is there any way to move all of the data that I currently have in the program to another computer, so that they don't have to start all over?

**Comment by martinb3** [comment]
Hi there -- yes! All of the files created by Egonet can be copied to another computer and easily loaded there. All of the needed files can be copied from the same directory as the study, under an "Interviews" folder.

Hope that helps!
