### ISSUE TITLE
Java error when pressing Raw Data and Summary Statistics button

### ISSUE THREAD

**Issue by ufchris** [egonet/egonet#8]
Hi Martin,

I'm at an anthro conference and some folks have been using Egonet.  They consistently getting an error when trying to export the Raw data and Summary Statistics.  They did a fake interview that has the problem.  I'll attach the ego and int files.

Actually it won't support those data types.  I'll e-mail them to you.

They want to know how they could share real data files in a secure way

**Comment by martinb3** [comment]
Hi Chris,

I'm able to get this to work -- _but_, you must create an "Interviews"
directory and put the interview file there. If you save the two files in
any old directory, with the structure that Egonet might not be expecting,
you get a Java error. I'm going to leave this issue open until we correct
the error message, at a minimum.

Hope this helps!

- Martin


On Fri, Nov 20, 2015 at 12:50 PM, ufchris <notifications@github.com> wrote:

> Hi Martin,
>
> I'm at an anthro conference and some folks have been using Egonet. They
> consistently getting an error when trying to export the Raw data and
> Summary Statistics. They did a fake interview that has the problem. I'll
> attach the ego and int files.
>
> Actually it won't support those data types. I'll e-mail them to you.
>
> They want to know how they could share real data files in a secure way
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egonet/egonet/issues/8>.
>



-- 
Martin B. Smith
martin@mbs3.org
