### ISSUE TITLE
Problem with Lontitudinal Interview

### ISSUE THREAD

**Issue by hopkin28** [egonet/egonet#9]
I'm piloting a longitudinal study designed to measure change in an individual's social network after they quit smoking. I used the question builder to create the survey for the first time point (T1). I would like to use the longitudinal option in the interview and analysis tool, but I'm having trouble getting it to work. Here are the steps I'm following:

File>New Interviewing Tool Window>Select Study>I select the T1 survey file>Start interview>Save new longitudinal interview>

Then I tried 2 things, neither of which worked:
1. I selected the interview for participant from T1>open and the data for the original file was erased and the survey began from the beginning just like in T1
2. I selected the interview for participant from T1 and added a 2 to the file name>open and the survey began from the beginning just like in T1

Any suggestions on what I'm doing wrong?

    Also, what is the benefit of using the longitudinal interview feature? My hope is that it would skip ego questions that are fixed and also would provide the previous alter list provided so ego doesn't need to give all the names again. 

Thanks,
Allison

**Comment by martinb3** [comment]
Hi Allison,

The purpose of the longitudinal functionality is to copy data from the
previous interview to the new one, as well as to ask additional questions
if any skip logic exists (I believe the option is called 'follow up only').
The first time through, you treat the interview just like a normal one, and
the second time through, you'd choose the longitudinal option when
prompted, and then save as a new file.

Hope this helps!

- Martin



On Thu, Dec 17, 2015 at 12:08 PM, hopkin28 <notifications@github.com> wrote:

> I'm piloting a longitudinal study designed to measure change in an
> individual's social network after they quit smoking I used the question
> builder to create the survey for the first time point (T1) I would like to
> use the longitudinal option in the interview and analysis tool, but I'm
> having trouble getting it to work Here are the steps I'm following:
>
> File>New Interviewing Tool Window>Select Study>I select the T1 survey
> file>Start interview>Save new longitudinal interview>
>
> Then I tried 2 things, neither of which worked:
> 1 I selected the interview for participant from T1>open and the data for
> the original file was erased and the survey began from the beginning just
> like in T1
> 2 I selected the interview for participant from T1 and added a 2 to the
> file name>open and the survey began from the beginning just like in T1
>
> Any suggestions on what I'm doing wrong?
>
> Also, what is the benefit of using the longitudinal interview feature? My hope is that it would skip ego questions that are fixed and also would provide the previous alter list provided so ego doesn't need to give all the names again
>
> Thanks,
> Allison
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egonet/egonet/issues/9>.
>



-- 
Martin B. Smith
martin@mbs3.org

**Comment by hopkin28** [comment]
Hi Martin,

I added a question to the survey in the question builder and selected up "follow up protocols" like you suggested. Then I completed a test interview. Next on wanted to test the longitudinal feature so I started the process to carry out a second interview. I selected the longitudinal option, selected the test interview file and renamed it. However, I got the following error: "The original interview you selected is corrupted. Will not proceed." Any suggestions for how to address this issue? 

thanks,

Allison

**Comment by hopkin28** [comment]
Hi Martin,

    I was able to fix my issue by removing the Egonet applications from my computer and downloading it again. The new test interview I created worked as you had instructed originally. 

    FYI for others who may be wanting to use this feature: The only data that was copied from the first interview to the second was the list of names created from the name generator question.  

    Thanks for all your help. I really appreciate it. 

best,
Allison

**Comment by martinb3** [comment]
Hi @hopkin28, I'm glad to hear downloaded the latest version fixed it! Thanks for the update! :)
